<?php

/**
 * !CAUTION! Autogenerated code that was generated by the 'configure-env.php' script.
 * All modifications directly applied to this file,
 * may break or badly influence the operability of the apps relying on the contents of this file.
 *
 * !DO NOT EDIT!
 * Unless there is someone standing behind you with a loaded shotgun ready to create a mess and still you have to know what your doing or...
 * -> !DO NOT EDIT!
 */

return array (
  'php' => '/usr/bin/php',
  'environment' => 'testing.development.vagrant',
  'base_href' => 'http://berlinonline.dev',
);